################################################################################
#
# mepa
#
################################################################################

MEPA_VERSION = f8aff2d6cf52e89e57ec68b24efec3e02260871e
MEPA_SITE = https://github.com/vjardin/mesa.git
MEPA_SITE_METHOD = git
MEPA_LICENSE = MIT
MEPA_LICENSE_FILES = LICENSE
MEPA_INSTALL_STAGING = YES
MEPA_SUPPORTS_IN_SOURCE_BUILD = NO

# vjardin/mesa vj_integration_allPR is a single integrated tree with mesa/,
# mepa/, meba/, phy_demo_appl/ as siblings; no separate MESA tarball is
# needed. mesa/demo/ builds both mesa-demo (unused) and mesa-cmd (the SPI-
# proxy client that replaces mesa-demo as PHY-config front-end).
MEPA_CONF_OPTS = -DMESA_OPSYS_LINUX:BOOL=ON \
				 -DBUILD_mepa:BOOL=ON \
				 -DBUILD_MESA_DEMO:BOOL=ON \
				 -Dvsc7558:BOOL=$(if $(BR2_PACKAGE_MEPA_VSC7558),ON,OFF) \
				 -Dlan966x:BOOL=$(if $(BR2_PACKAGE_MEPA_LAN966x),ON,OFF) \
				 -DBUILD_MEBA_edsx:BOOl=$(if $(BR2_PACKAGE_MEPA_EDSX),ON,OFF) \
				 -DBUILD_MEBA_eds2:BOOl=$(if $(BR2_PACKAGE_MEPA_EDS2),ON,OFF) \
				 -DBUILD_mepa_drv_vtss:BOOl=$(if $(BR2_PACKAGE_MEPA_VTSS_1G),ON,OFF) \
				 -DBUILD_mepa_drv_vtss_10g_only:BOOl=$(if $(BR2_PACKAGE_MEPA_VTSS_10G),ON,OFF) \
				 -DBUILD_mepa_drv_vtss_ts:BOOl=$(if $(BR2_PACKAGE_MEPA_VTSS_TS),ON,OFF) \
				 -DBUILD_mepa_drv_vtss_10g_ts:BOOl=$(if $(BR2_PACKAGE_MEPA_VTSS_10G_TS),ON,OFF) \
				 -DBUILD_mepa_drv_vtss_10g_macsec_ts:BOOl=$(if $(BR2_PACKAGE_MEPA_VTSS_10G_MACSEC_TS),ON,OFF)

MEPA_BUILD_AQR=$(if $(BR2_PACKAGE_MEPA_AQR),ON,OFF)
MEPA_CONF_OPTS += -DBUILD_mepa_drv_aqr:BOOL=$(MEPA_BUILD_AQR) \
				  -DMEPA_aqr:BOOL=$(MEPA_BUILD_AQR)

MEPA_BUILD_INTEL=$(if $(BR2_PACKAGE_MEPA_INTEL),ON,OFF)
MEPA_CONF_OPTS += -DBUILD_mepa_drv_intel:BOOL=$(MEPA_BUILD_INTEL) \
				  -DMEPA_gpy211:BOOL=$(MEPA_BUILD_INTEL)

MEPA_BUILD_KSZ9031=$(if $(BR2_PACKAGE_MEPA_KSZ9031),ON,OFF)
MEPA_CONF_OPTS += -DBUILD_mepa_drv_ksz9031:BOOL=$(MEPA_BUILD_KSZ9031) \
				  -DMEPA_ksz9031:BOOL=$(MEPA_BUILD_KSZ9031)

MEPA_BUILD_LAN80XX_TS=$(if $(BR2_PACKAGE_MEPA_LAN80XX_TS),ON,OFF)
MEPA_CONF_OPTS += -DBUILD_mepa_drv_lan80xx_ts:BOOL=$(MEPA_BUILD_LAN80XX_TS) \
				  -DMEPA_lan80xx_ts:BOOL=$(MEPA_BUILD_LAN80XX_TS)
ifeq ($(BR2_PACKAGE_MEPA_LAN80XX_TS),y)
MEPA_CONF_OPTS += -DMEPA_lan80xx_DFU_PROFILING:BOOL=$(if $(BR2_PACKAGE_MEPA_LAN80XX_DFU_PROFILING),ON,OFF)
endif

MEPA_BUILD_LAN80XX_TS_MSEC=$(if $(BR2_PACKAGE_MEPA_LAN80XX_TS_MSEC),ON,OFF)
MEPA_CONF_OPTS += -DBUILD_mepa_drv_lan80xx_ts_msec:BOOL=$(MEPA_BUILD_LAN80XX_TS_MSEC) \
				  -DMEPA_lan80xx_ts_msec:BOOL=$(MEPA_BUILD_LAN80XX_TS_MSEC)

MEPA_BUILD_LAN8770=$(if $(BR2_PACKAGE_MEPA_LAN8770),ON,OFF)
MEPA_CONF_OPTS += -DBUILD_mepa_drv_lan8770:BOOL=$(MEPA_BUILD_LAN8770) \
				  -DMEPA_lan8770:BOOL=$(MEPA_BUILD_LAN8770)

MEPA_BUILD_LAN8814=$(if $(BR2_PACKAGE_MEPA_LAN8814),ON,OFF)
MEPA_CONF_OPTS += -DBUILD_mepa_drv_lan8814:BOOL=$(MEPA_BUILD_LAN8814) \
				  -DMEPA_lan8814:BOOL=$(MEPA_BUILD_LAN8814)

MEPA_BUILD_LAN8814_LIGHT=$(if $(BR2_PACKAGE_MEPA_LAN8814_LIGHT),ON,OFF)
MEPA_CONF_OPTS += -DBUILD_mepa_drv_lan8814_light:BOOL=$(MEPA_BUILD_LAN8814_LIGHT) \
				  -DMEPA_lan8814_light:BOOL=$(MEPA_BUILD_LAN8814_LIGHT)

MEPA_BUILD_LAN884X=$(if $(BR2_PACKAGE_MEPA_LAN884x),ON,OFF)
MEPA_CONF_OPTS += -DBUILD_mepa_drv_lan884x:BOOL=$(MEPA_BUILD_LAN884X) \
				  -DMEPA_lan884x:BOOL=$(MEPA_BUILD_LAN884X)

MEPA_BUILD_LAN867X=$(if $(BR2_PACKAGE_MEPA_LAN867X),ON,OFF)
MEPA_CONF_OPTS += -DBUILD_mepa_drv_lan867x:BOOL=$(MEPA_BUILD_LAN867X) \
				  -DMEPA_lan867x:BOOL=$(MEPA_BUILD_LAN867X)
ifeq ($(BR2_PACKAGE_MEPA_LAN867X),y)
MEPA_CONF_OPTS += -DMEPA_LAN867X_PHY_MAX:STRING=$(BR2_PACKAGE_MEPA_LAN867X_PHY_MAX) \
				  -DMEPA_LAN867X_STATIC_MEM:BOOL=$(if $(BR2_PACKAGE_MEPA_LAN867X_STATIC_MEM),ON,OFF)
endif

MEPA_BUILD_LAN8X8X=$(if $(BR2_PACKAGE_MEPA_LAN8X8X),ON,OFF)
MEPA_CONF_OPTS += -DBUILD_mepa_drv_lan8x8x:BOOL=$(MEPA_BUILD_LAN8X8X) \
				  -DMEPA_lan8x8x:BOOL=$(MEPA_BUILD_LAN8X8X)
ifeq ($(BR2_PACKAGE_MEPA_LAN8X8X),y)
MEPA_CONF_OPTS += -DMEPA_lan8x8x_phy_max:STRING=$(BR2_PACKAGE_MEPA_LAN8X8X_PHY_MAX) \
				  -DMEPA_lan8x8x_static_mem:BOOL=$(if $(BR2_PACKAGE_MEPA_LAN8X8X_STATIC_MEM),ON,OFF)
endif

MEPA_BUILD_LAN887X=$(if $(BR2_PACKAGE_MEPA_LAN887X),ON,OFF)
MEPA_CONF_OPTS += -DBUILD_mepa_drv_lan887x:BOOL=$(MEPA_BUILD_LAN887X) \
				  -DMEPA_lan887x:BOOL=$(MEPA_BUILD_LAN887X)
ifeq ($(BR2_PACKAGE_MEPA_LAN887X),y)
MEPA_CONF_OPTS += -DMEPA_lan887x_phy_max:STRING=$(BR2_PACKAGE_MEPA_LAN887X_PHY_MAX) \
				  -DMEPA_lan887x_static_mem:BOOL=$(if $(BR2_PACKAGE_MEPA_LAN887X_STATIC_MEM),ON,OFF)
endif

MEPA_BUILD_VTSS_CUSTOM=$(if $(BR2_PACKAGE_MEPA_VTSS_CUSTOM),ON,OFF)
MEPA_CONF_OPTS += -DBUILD_mepa_drv_vtss_custom:BOOL=$(BR2_PACKAGE_MEPA_VTSS_CUSTOM) \
				  -DMEPA_vtss:BOOL=$(BR2_PACKAGE_MEPA_VTSS_CUSTOM)
ifeq ($(BR2_PACKAGE_MEPA_VTSS_CUSTOM),y)
MEPA_CONF_OPTS += -DMEPA_vtss_opt_10g:BOOL=$(if $(BR2_PACKAGE_MEPA_VTSS_CUSTOM_10G),ON,OFF) \
				  -DMEPA_vtss_opt_1g:BOOL=$(if $(BR2_PACKAGE_MEPA_VTSS_CUSTOM_1G),ON,OFF) \
				  -DMEPA_vtss_opt_macsec:BOOL=$(if $(BR2_PACKAGE_MEPA_VTSS_CUSTOM_MACSEC),ON,OFF) \
				  -DMEPA_vtss_opt_ts:BOOL=$(if $(BR2_PACKAGE_MEPA_VTSS_CUSTOM_TS),ON,OFF) \
				  -DMEPA_vtss_opt_cnt:STRING=$(BR2_PACKAGE_MEPA_VTSS_CUSTOM_CNT)
endif

MEPA_RUBY_DEPS = parslet
define MEPA_RUBY_DEPS_INSTALL
	$(foreach dep,$(MEPA_RUBY_DEPS), \
		$(HOST_DIR)/bin/gem install $(dep)
	)
endef
MEPA_PRE_CONFIGURE_HOOKS += MEPA_RUBY_DEPS_INSTALL

MEPA_DEPENDENCIES += host-ruby json-c mepa-spidev-proxy

define MEPA_REMOVE_COMMON_SRCS
	rm -rf $(TARGET_DIR)/usr/share/mepa
endef
MEPA_TARGET_FINALIZE_HOOKS += MEPA_REMOVE_COMMON_SRCS

$(eval $(cmake-package))
